### ISSUE TITLE
Glow "&g" dont work - Gloss holograms

### ISSUE THREAD

**Issue by FoviOX** [VolmitSoftware/Gloss#81]
When I remove "&g" from hologram line, line appear. But when I add "&g" to hologram line, line disappear.
(Click on image to see video)
<div align="left">
  <a href="https://www.youtube.com/watch?v=GEQvj-KjAvs"><img src="https://img.youtube.com/vi/GEQvj-KjAvs/0.jpg" alt="Click to see video"></a>
</div>

**Comment by DavidRockin** [comment]
Hi, can you send your console log via Pastebin. Thanks

**Comment by FoviOX** [comment]
[2019-07-23-4.log.gz](https://github.com/VolmitSoftware/Gloss/files/3423534/2019-07-23-4.log.gz)
![Screenshot_14](https://user-images.githubusercontent.com/33469628/61738045-19220080-ad92-11e9-9474-c0915b394f31.jpg)

**Comment by Andre601** [comment]
Since this is somewhat similar will I post this here to have it "logged"
The glow effect (the particles) are misspositioned on the hologram. Instead of being where the text is is the particle next to the floor (or just a few blocks below)

Server: 1.14.4 PaperMC server (git-Paper-146)

![2019-07-28_14 42 07](https://user-images.githubusercontent.com/11576465/62006805-f43cdd00-b145-11e9-801b-867cc21607b6.png)

**Comment by DavidRockin** [comment]
Holograms have been fixed for 1.3.1
